version: '3'
services:
  app:
    image: node:20-alpine
    command: sh -c "pnpm install && pnpm run build && pnpm run serve"
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./:/app
