version: '3'
services:
  app:
    image: node:20-alpine
    command: sh -c "corepack enable && corepack prepare pnpm@8  && pnpm install && pnpm run build && pnpm run serve"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app